<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LinkedIn.Application\LinkedIn.Application.csproj" />
    <ProjectReference Include="..\LinkedIn.Domain\LinkedIn.Domain.csproj" />
  </ItemGroup>

</Project>
